# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SpartanJ.ecode
PackageVersion: 0.9.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ecode/ecode.exe
InstallModes:
- silent
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2026-10-08
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/SpartanJ/ecode/releases/download/ecode-0.9.0/ecode-windows-0.9.0-x86_64.zip
  InstallerSha256: 064EFDD8E2F4E7D54947B4EBFE4A08EA2DC905374BC712DED8CD13EA43686D14
- Architecture: arm64
  InstallerUrl: https://github.com/SpartanJ/ecode/releases/download/ecode-0.9.0/ecode-windows-0.9.0-arm64.zip
  InstallerSha256: 55966EF6DD489C4CDC8E9F836DBF02F90DC443A9B7DD6AC410FEBE681BBFDA00
ManifestType: installer
ManifestVersion: 1.12.0
